spring:
  application:
    name: gym-system-service

  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: admin
    password: admin
    destination: workload

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

#logging:
#  level:
#    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

server:
  servlet:
    context-path: /api

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/dev_gym_system_db
    username: devuser
    password: devpass

---
spring:
  config:
    activate:
      on-profile: stg
  datasource:
    url: jdbc:mysql://localhost:3306/stg_gym_system_db
    username: stguser
    password: stgpass

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://prod-db-server:3306/prod_gym_system_db
    username: produser
    password: prodpass
